### ISSUE TITLE
Binder does not launch Julia kernel. 

### ISSUE THREAD

**Issue by akabla** [moustachio-belvedere/JuliaPackageDemo.jl#1]
Julia 1.4 needs to be in compat in project.toml I think.

https://mybinder.readthedocs.io/en/latest/howto/languages.html

**Comment by moustachio-belvedere** [comment]
Thanks for linking to that, I had not seen it. I tried adding compat info but it still seems to be not installing Julia in the vm. Will look into this more in the week. Seems to be working fine in the Literate.jl example so there must be a way!

**Comment by moustachio-belvedere** [comment]
Ah I realised what was wrong, a project.toml specifically for Binder has to be placed in gh-pages branch of the repo as this is the branch the binder accesses. However, this test package 'JuliaPackageDemo' isn't on the julia package registry so I'm not sure how Binder could find it. This won't be a problem on RHEOS as it's on the package registry. I'll see if there's a way round the problem on this repo at some point.

Update: Julia kernel loading fine now but as mentioned above, cannot access JuliaPackageDemo as it's not in Julia package repo.

**Comment by moustachio-belvedere** [comment]
All fixed now, for the Project.toml in the gh-pages branch I just had to be careful to use

`Pkg.add(PackageSpec(url="https://github.com/moustachio-belvedere/JuliaPackageDemo.jl", rev="master"))`

so that it will look in the correct place (not central Julia package registry) for the package when it installs dependencies. This would only be necessary for RHEOS if we want to test binder on the latest non-stable versions, which I don't think we do.
